const INPUT_TODO = 'INPUT_TODO'
const CREATE_TODO = 'CREATE_TODO'
const OPEN_CREATE_FORM = 'OPEN_CREATE_FORM'
const OPEN_EDIT_FORM = 'OPEN_EDIT_FORM'
const CLOSE_FORM = 'CLOSE_FORM'
const TOGGLE_TODO = 'TOGGLE_TODO'
const DELETE_TODO = 'DELETE_TODO'
const EDIT_TODO = 'EDIT_TODO'
const FILTER_TODO = 'FILTER_TODO'

export {
    INPUT_TODO,
    CREATE_TODO,
    OPEN_CREATE_FORM,
    OPEN_EDIT_FORM,
    CLOSE_FORM,
    TOGGLE_TODO,
    DELETE_TODO,
    EDIT_TODO,
    FILTER_TODO,
}